version: '3.3' # 兼容旧版docker-compose
services:
  certd:
    # 镜像                                                  #  ↓↓↓↓↓ ---- 镜像版本号，建议改成固定版本号
    image: registry.cn-shenzhen.aliyuncs.com/handsfree/certd:latest
    container_name: certd # 容器名
    restart: unless-stopped # 自动重启
    volumes:
      #   ↓↓↓↓↓ -------------------------------------------------------- 数据库以及证书存储路径,默认存在宿主机的/data/certd/目录下，【您需要定时备份此目录，以保障数据容灾】
      - /data/certd:/app/data
    ports: # 端口映射
      #  ↓↓↓↓ ---------------------------------------------------------- 如果端口有冲突，可以修改第一个7001为其他不冲突的端口号
      - "7001:7001"
      #  ↓↓↓↓ ---------------------------------------------------------- https端口，可以根据实际情况，是否暴露相关服务端口
      - "7002:7002"
    dns:
      #  ↓↓↓↓ ---------------------------------------------------------- 如果出现getaddrinfo ENOTFOUND等错误，可以尝试修改或注释dns配置
      - 223.5.5.5
      - 223.6.6.6
      #  ↓↓↓↓ ---------------------------------------------------------- 如果你服务器部署在国外，可以用8.8.8.8替换上面的dns
#      - 8.8.8.8
#      - 8.8.4.4
#    extra_hosts:
      #  ↓↓↓↓ ---------------------------------------------------------- 这里可以配置自定义hosts，外网域名可以指向本地局域网ip地址
#      - "localdomain.comm:192.168.1.3"
    environment: # 环境变量
      - TZ=Asia/Shanghai
      # 设置环境变量即可自定义certd配置
      # 配置项见： packages/ui/certd-server/src/config/config.default.ts
      # 配置规则： certd_ + 配置项, 点号用_代替

                           #  ↓↓↓↓  ------------------------------------ 这里可以设置http代理
      #- HTTPS_PROXY=http://xxxxxx:xx
      #- HTTP_PROXY=http://xxxxxx:xx
      #                               ↓↓↓↓ ----------------------------- 如果忘记管理员密码，可以设置为true，重启之后，管理员密码将改成123456，然后请及时修改回false
      - certd_system_resetAdminPasswd=false
      #                                  ↓↓↓↓ -------------------------- 如果设置为true，启动后所有配置了cron的流水线任务都将被立即触发一次
      - certd_cron_immediateTriggerOnce=false
      #                            ↓↓↓↓ -------------------------------- 配置证书和key，则表示https方式启动，使用https协议访问，https://your.domain:7001
      #- certd_koa_key=./data/ssl/cert.key
      #- certd_koa_cert=./data/ssl/cert.crt

      #                             ↓↓↓↓ ------------------------------- 使用postgresql数据库
#      - certd_flyway_scriptDir=./db/migration-pg               # 升级脚本目录
#      - certd_typeorm_dataSource_default_type=postgres         # 数据库类型
#      - certd_typeorm_dataSource_default_host=localhost        # 数据库地址
#      - certd_typeorm_dataSource_default_port=5433             # 数据库端口
#      - certd_typeorm_dataSource_default_username=postgres     # 用户名
#      - certd_typeorm_dataSource_default_password=yourpasswd   # 密码
#      - certd_typeorm_dataSource_default_database=certd        # 数据库名


